export default {
    profileimage: "",
    profilePhoto: "",
    firstName: "",
    lastName: "",
    gender: "",
    phoneNumber: "",
    email: "",
    bio: "",
    search: "",
    houseNumber: "",
    area: "",
    landMark: "",
    country: "",
    city: "",
    state: "",
    services: [],
    price: "",
    isCertified: false,
    uploadcertificate: "",
    experience: "",
    style: "",
    workingstate: "",
    brand: "",
    profile: "",
    photos: [],
    videos: [],
    ismobilevarified: false


}